/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica.Licencias;

import java.util.Date;
import CapaGrafica.ControlesAdmin;
import CapaLogica.licencia;
import CapaLogica.fachada;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/**
 *
 * @author tomas
 */
public class Licencias extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Licencias.class.getName());
    SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form AddLicencia
     */
    public Licencias() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FechaDeInico = new javax.swing.JLabel();
        Ingreso_FechaInicio = new javax.swing.JTextField();
        FechaDeFinalizacion = new javax.swing.JLabel();
        Ingreso_FechaFinal = new javax.swing.JTextField();
        Razon = new javax.swing.JLabel();
        Ingreso_Razon = new javax.swing.JTextField();
        Aclaracion = new javax.swing.JLabel();
        Ingreso_Aclaracion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        VolverBTN = new javax.swing.JButton();
        AniadirBTN = new javax.swing.JButton();
        FechaDeInico1 = new javax.swing.JLabel();
        IngresarCI = new javax.swing.JTextField();
        BuscarLicenciaBTN = new javax.swing.JButton();
        EliminarBTN = new javax.swing.JButton();
        ModificarBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(77, 130, 244));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Licencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        FechaDeInico.setForeground(new java.awt.Color(0, 0, 0));
        FechaDeInico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaDeInico.setText("Fecha de Inicio");

        Ingreso_FechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_FechaInicioActionPerformed(evt);
            }
        });

        FechaDeFinalizacion.setForeground(new java.awt.Color(0, 0, 0));
        FechaDeFinalizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaDeFinalizacion.setText("Fecha de Finalización");

        Ingreso_FechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_FechaFinalActionPerformed(evt);
            }
        });

        Razon.setForeground(new java.awt.Color(0, 0, 0));
        Razon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Razon.setText("Razón");

        Ingreso_Razon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_RazonActionPerformed(evt);
            }
        });

        Aclaracion.setForeground(new java.awt.Color(0, 0, 0));
        Aclaracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aclaracion.setText("Aclaración (Opcional)");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("*Fechas deben tener el formato YYYY/MM/DD");
        jLabel3.setToolTipText("");

        VolverBTN.setBackground(new java.awt.Color(77, 130, 244));
        VolverBTN.setForeground(new java.awt.Color(0, 0, 0));
        VolverBTN.setText("Volver");
        VolverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBTNActionPerformed(evt);
            }
        });

        AniadirBTN.setBackground(new java.awt.Color(77, 130, 244));
        AniadirBTN.setForeground(new java.awt.Color(0, 0, 0));
        AniadirBTN.setText("Añadir Licencia");
        AniadirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AniadirBTNActionPerformed(evt);
            }
        });

        FechaDeInico1.setForeground(new java.awt.Color(0, 0, 0));
        FechaDeInico1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaDeInico1.setText("Cedula");

        IngresarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarCIActionPerformed(evt);
            }
        });

        BuscarLicenciaBTN.setBackground(new java.awt.Color(77, 130, 244));
        BuscarLicenciaBTN.setForeground(new java.awt.Color(0, 0, 0));
        BuscarLicenciaBTN.setText("Buscar Licencia");
        BuscarLicenciaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLicenciaBTNActionPerformed(evt);
            }
        });

        EliminarBTN.setBackground(new java.awt.Color(77, 130, 244));
        EliminarBTN.setForeground(new java.awt.Color(0, 0, 0));
        EliminarBTN.setText("Eliminar Licencia");
        EliminarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBTNActionPerformed(evt);
            }
        });

        ModificarBTN.setBackground(new java.awt.Color(77, 130, 244));
        ModificarBTN.setForeground(new java.awt.Color(0, 0, 0));
        ModificarBTN.setText("Modificar Licencia");
        ModificarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBTNActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para buscar y eliminar se debe ingresar: \nCedula y Fecha de Inicio\n\nPara modificar es recomendado \nprimero buscar la licencia y despues modificarla");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AniadirBTN)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Ingreso_Aclaracion)
                        .addComponent(Aclaracion, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaDeInico1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IngresarCI)
                            .addComponent(FechaDeInico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ingreso_FechaInicio)
                            .addComponent(FechaDeFinalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ingreso_FechaFinal)
                            .addComponent(Razon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarLicenciaBTN)
                            .addComponent(EliminarBTN)
                            .addComponent(ModificarBTN)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ingreso_Razon, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VolverBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(FechaDeInico1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaDeInico)
                            .addComponent(BuscarLicenciaBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ingreso_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarBTN))
                        .addGap(18, 18, 18)
                        .addComponent(FechaDeFinalizacion))
                    .addComponent(ModificarBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ingreso_FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Razon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ingreso_Razon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Aclaracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ingreso_Aclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverBTN)
                    .addComponent(AniadirBTN))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingreso_FechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_FechaInicioActionPerformed

    }//GEN-LAST:event_Ingreso_FechaInicioActionPerformed

    private void Ingreso_FechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_FechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingreso_FechaFinalActionPerformed

    private void VolverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBTNActionPerformed
        // TODO add your handling code here:
        ControlesAdmin con = new ControlesAdmin();
        dispose();
        setVisible(false);
        con.setVisible(true);

    }//GEN-LAST:event_VolverBTNActionPerformed

    private void AniadirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AniadirBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || Ingreso_FechaInicio.getText().isEmpty() || Ingreso_FechaFinal.getText().isEmpty() || Ingreso_Razon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios");
        } else {
            licencia inas = new licencia();
            try {

                String razon = Ingreso_Razon.getText();
                inas.setRazon(razon);

                if (!Ingreso_Aclaracion.getText().isEmpty()) {
                    String aclaracion = Ingreso_Aclaracion.getText();
                    inas.setAclaracion(aclaracion);
                } else {
                    inas.setAclaracion("N/A");
                }

                formato.setLenient(false);
                try {
                    Date inicio = formato.parse(Ingreso_FechaInicio.getText());
                    java.sql.Date fechaSQL = new java.sql.Date(inicio.getTime());
                    inas.setPeriodoInicio(fechaSQL);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "La fecha de inicio no esta en el formato correcto. El formato es yyyy/mm/dd");
                }

                try {

                    Date fin = formato.parse(Ingreso_FechaFinal.getText());
                    java.sql.Date fechaSQL = new java.sql.Date(fin.getTime());
                    inas.setPeriodoFin(fechaSQL);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "La fecha de fin no esta en el formato correcto. El formato es yyyy/mm/dd");
                }

                try {
                    int CI = Integer.parseInt(IngresarCI.getText());
                    inas.setCI(CI);
                } catch (NumberFormatException num) {
                    JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");
                }
                fachada.IngresarLicencia(inas);
                JOptionPane.showMessageDialog(this, "Datos guardados correctamente");

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar los datos");

            }

        }
    }//GEN-LAST:event_AniadirBTNActionPerformed

    private void IngresarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCIActionPerformed
    }//GEN-LAST:event_IngresarCIActionPerformed
    private void Ingreso_RazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_RazonActionPerformed
    }//GEN-LAST:event_Ingreso_RazonActionPerformed


    private void BuscarLicenciaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLicenciaBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || Ingreso_FechaInicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cedula y fecha de inicio no pueden estar vacios para buscar licencias");
        } else {
            licencia buscarLicencia = new licencia();
            try {
                int CI = Integer.parseInt(IngresarCI.getText());
                buscarLicencia.setCI(CI);
                formato.setLenient(false);
                try {
                    Date inicio = formato.parse(Ingreso_FechaInicio.getText());
                    java.sql.Date fechaSQL = new java.sql.Date(inicio.getTime());
                    buscarLicencia.setPeriodoInicio(fechaSQL);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "La fecha de inicio no esta en el formato correcto. El formato es yyyy/mm/dd");
                }

                fachada.BuscarLicencia(buscarLicencia);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Pone un numero");
            } catch (Exception ex) {
                System.getLogger(Licencias.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            java.sql.Date fechaFin= new java.sql.Date(buscarLicencia.getPeriodoFin().getTime());
            java.util.Date fechaUtil = new java.util.Date(fechaFin.getTime());
            String FehcaFormateada= formato.format(fechaUtil);
            String razon = buscarLicencia.getRazon();
            String aclaracion = buscarLicencia.getAclaracion();
            
            Ingreso_FechaFinal.setText(FehcaFormateada);
            Ingreso_Razon.setText(razon);
            Ingreso_Aclaracion.setText(aclaracion);

        }
    }//GEN-LAST:event_BuscarLicenciaBTNActionPerformed

    private void EliminarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBTNActionPerformed
        if (IngresarCI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La cedula del profe es necesaria para poder eliminarlo");
        } else {
            licencia EliminarLicencia = new licencia();

            try {
                int CI = Integer.parseInt(IngresarCI.getText());
                EliminarLicencia.setCI(CI);
            } catch (NumberFormatException num) {
                JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");

            }
            try {
                Date inicio = formato.parse(Ingreso_FechaInicio.getText());
                java.sql.Date fechaSQL = new java.sql.Date(inicio.getTime());
                EliminarLicencia.setPeriodoInicio(fechaSQL);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "La fecha de inicio no esta en el formato correcto. El formato es yyyy/mm/dd");
            }

            try {
                java.util.Date fechaInicio = EliminarLicencia.getPeriodoInicio(); // java.util.Date
                java.sql.Date fechaSQL = new java.sql.Date(fechaInicio.getTime()); // java.sql.Date
                fachada.EliminarLicencia(EliminarLicencia.getCI(), fechaSQL);

            } catch (Exception ex) {
                System.getLogger(Licencias.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(this, "No se pudo borrar los datos");

            }
            JOptionPane.showMessageDialog(this, "Se pudo borrar los datos");

    }     }//GEN-LAST:event_EliminarBTNActionPerformed

    private void ModificarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || Ingreso_FechaInicio.getText().isEmpty() || Ingreso_FechaFinal.getText().isEmpty() || Ingreso_Razon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios");
        } else {
            
            try {
                licencia inas = new licencia();
                String razon = Ingreso_Razon.getText();
                inas.setRazon(razon);

                if (!Ingreso_Aclaracion.getText().isEmpty()) {
                    String aclaracion = Ingreso_Aclaracion.getText();
                    inas.setAclaracion(aclaracion);
                } else {
                    inas.setAclaracion("N/A");
                }

                formato.setLenient(false);
                try {
                    Date inicio = formato.parse(Ingreso_FechaInicio.getText());
                    java.sql.Date fechaSQL = new java.sql.Date(inicio.getTime());
                    inas.setPeriodoInicio(fechaSQL);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "La fecha de inicio no esta en el formato correcto. El formato es yyyy/mm/dd");
                }

                try {

                    Date fin = formato.parse(Ingreso_FechaFinal.getText());
                    java.sql.Date fechaSQL = new java.sql.Date(fin.getTime());
                    inas.setPeriodoFin(fechaSQL);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "La fecha de fin no esta en el formato correcto. El formato es yyyy/mm/dd");
                }

                try {
                    int CI = Integer.parseInt(IngresarCI.getText());
                    inas.setCI(CI);
                } catch (NumberFormatException num) {
                    JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");
                }
                int ci=inas.getCI();
                String obser=inas.getAclaracion();
                Date fechaFin=inas.getPeriodoFin();
                java.sql.Date fechaFinSQL = new java.sql.Date(fechaFin.getTime()); // java.sql.Date
                Date fechaIni=inas.getPeriodoInicio();
                java.sql.Date fechaIniSQL = new java.sql.Date(fechaIni.getTime()); // java.sql.Date
                String Razon=inas.getRazon();
                
                fachada.ModificarLicencia(ci,obser,fechaFinSQL,fechaIniSQL,Razon);
                JOptionPane.showMessageDialog(this, "Datos modificados correctamente");

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar los cambios");

            }

        }
    }//GEN-LAST:event_ModificarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Licencias().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aclaracion;
    private javax.swing.JButton AniadirBTN;
    private javax.swing.JButton BuscarLicenciaBTN;
    private javax.swing.JButton EliminarBTN;
    private javax.swing.JLabel FechaDeFinalizacion;
    private javax.swing.JLabel FechaDeInico;
    private javax.swing.JLabel FechaDeInico1;
    private javax.swing.JTextField IngresarCI;
    private javax.swing.JTextField Ingreso_Aclaracion;
    private javax.swing.JTextField Ingreso_FechaFinal;
    private javax.swing.JTextField Ingreso_FechaInicio;
    private javax.swing.JTextField Ingreso_Razon;
    private javax.swing.JButton ModificarBTN;
    private javax.swing.JLabel Razon;
    private javax.swing.JButton VolverBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
