/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica.Profesor;

import CapaGrafica.ControlesAdmin;
import javax.swing.JOptionPane;
import CapaLogica.Profe;
import CapaLogica.fachada;

/**
 *
 * @author Rodri
 */
public class Profesor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profesor.class.getName());

    /**
     * Creates new form AddProfesor
     */
    public Profesor() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IngresarCI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IngresarNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IngresarApellido = new javax.swing.JTextField();
        VolverBTN = new javax.swing.JToggleButton();
        AgregarDocenteBTN = new javax.swing.JToggleButton();
        EliminarDocenteBTN = new javax.swing.JToggleButton();
        BuscarDocenteBTN = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        ModDocenteBTN = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(77, 130, 244));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Profesor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cedula");

        IngresarCI.setBackground(new java.awt.Color(204, 204, 204));
        IngresarCI.setForeground(new java.awt.Color(0, 0, 0));
        IngresarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarCIActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");

        IngresarNombre.setBackground(new java.awt.Color(204, 204, 204));
        IngresarNombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido");

        IngresarApellido.setBackground(new java.awt.Color(204, 204, 204));
        IngresarApellido.setForeground(new java.awt.Color(0, 0, 0));

        VolverBTN.setBackground(new java.awt.Color(77, 130, 244));
        VolverBTN.setForeground(new java.awt.Color(0, 0, 0));
        VolverBTN.setText("Volver");
        VolverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBTNActionPerformed(evt);
            }
        });

        AgregarDocenteBTN.setBackground(new java.awt.Color(77, 130, 244));
        AgregarDocenteBTN.setForeground(new java.awt.Color(0, 0, 0));
        AgregarDocenteBTN.setText("Ingresar docente nuevo");
        AgregarDocenteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDocenteBTNActionPerformed(evt);
            }
        });

        EliminarDocenteBTN.setBackground(new java.awt.Color(77, 130, 244));
        EliminarDocenteBTN.setForeground(new java.awt.Color(0, 0, 0));
        EliminarDocenteBTN.setText("Eliminar Docente");
        EliminarDocenteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDocenteBTNActionPerformed(evt);
            }
        });

        BuscarDocenteBTN.setBackground(new java.awt.Color(77, 130, 244));
        BuscarDocenteBTN.setForeground(new java.awt.Color(0, 0, 0));
        BuscarDocenteBTN.setText("Buscar");
        BuscarDocenteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDocenteBTNActionPerformed(evt);
            }
        });

        ModDocenteBTN.setBackground(new java.awt.Color(77, 130, 244));
        ModDocenteBTN.setForeground(new java.awt.Color(0, 0, 0));
        ModDocenteBTN.setText("Modificar Docente");
        ModDocenteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModDocenteBTNActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Si quieres eliminar o buscar debes primero introducir una cedula.\nPara modificar un profesor es recomendado primero\nbuscar y despues modificar");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(VolverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(AgregarDocenteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(IngresarApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addComponent(IngresarNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IngresarCI, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ModDocenteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarDocenteBTN)
                    .addComponent(BuscarDocenteBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarDocenteBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ModDocenteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarDocenteBTN)
                    .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngresarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VolverBTN)
                            .addComponent(AgregarDocenteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BuscarDocenteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDocenteBTNActionPerformed
        if (IngresarCI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cedula no puede estar vacia para buscar");
        } else {
            Profe BuscarProfe = new Profe();
            try {
                int CI = Integer.parseInt(IngresarCI.getText());
                BuscarProfe.setCI(CI);

 
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Pone un numero");
            }
            try {
                           Profe Bus=fachada.BuscarProfe(BuscarProfe);
                           String Nombre = Bus.getNombre();
            String Apellido = Bus.getApellido();
            IngresarNombre.setText(Nombre);
            IngresarApellido.setText(Apellido);
            } catch (Exception ex) {
                System.getLogger(Profesor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }
    }//GEN-LAST:event_BuscarDocenteBTNActionPerformed

    private void EliminarDocenteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocenteBTNActionPerformed
        if (IngresarCI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La cedula del profe es necesaria para poder eliminarlo");
        } else {
            Profe EliminarProfe = new Profe();

            try {
                int CI = Integer.parseInt(IngresarCI.getText());
                EliminarProfe.setCI(CI);
            } catch (NumberFormatException num) {
                JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");

            }
            try {
                fachada.EliminarProfe(EliminarProfe);

            } catch (Exception ex) {
                System.getLogger(Profesor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(this, "No se pudo borrar los datos");

            }
            JOptionPane.showMessageDialog(this, "Se pudo borrar los datos");

        }
    }//GEN-LAST:event_EliminarDocenteBTNActionPerformed

    private void AgregarDocenteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDocenteBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || IngresarApellido.getText().isEmpty() || IngresarNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios");
        } else {
            Profe prof = new Profe();
            try {
                String nombre = IngresarNombre.getText();
                prof.setNombre(nombre);
                String apellido = IngresarApellido.getText();
                prof.setApellido(apellido);
                try {
                    int CI = Integer.parseInt(IngresarCI.getText());
                    prof.setCI(CI);
                } catch (NumberFormatException num) {
                    JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");
                }
                
                fachada.IngresarProfe(prof);
                
                JOptionPane.showMessageDialog(this, "Datos guardados correctamente");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar los datos");

            }

        }

    }//GEN-LAST:event_AgregarDocenteBTNActionPerformed

    private void VolverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBTNActionPerformed
        dispose();
        setVisible(false);

        CapaGrafica.ControlesAdmin volver = new ControlesAdmin();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverBTNActionPerformed

    private void IngresarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarCIActionPerformed

    private void ModDocenteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModDocenteBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || IngresarApellido.getText().isEmpty() || IngresarNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios para modificar");
        } else {
            Profe prof = new Profe();
            try {
                String nombre = IngresarNombre.getText();
                prof.setNombre(nombre);
                String apellido = IngresarApellido.getText();
                prof.setApellido(apellido);
                try {
                    int CI = Integer.parseInt(IngresarCI.getText());
                    prof.setCI(CI);
                } catch (NumberFormatException num) {
                    JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");
                }
                fachada.ModificarProfe(prof.getCI(), prof.getNombre(), prof.getApellido());
                JOptionPane.showMessageDialog(this, "Datos modicicados correctamente");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar los cambios");

            }

        }    }//GEN-LAST:event_ModDocenteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profesor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgregarDocenteBTN;
    private javax.swing.JToggleButton BuscarDocenteBTN;
    private javax.swing.JToggleButton EliminarDocenteBTN;
    private javax.swing.JTextField IngresarApellido;
    private javax.swing.JTextField IngresarCI;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JToggleButton ModDocenteBTN;
    private javax.swing.JToggleButton VolverBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
