/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica.Curso;

import CapaGrafica.ControlesAdmin;
import CapaLogica.curso;
import CapaLogica.fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodri
 */
public class Cursos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(curso.class.getName());

    /**
     * Creates new form AddProfesor
     */
    public Cursos() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IngresarCI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IngresarMateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IngresarGrupo = new javax.swing.JTextField();
        VolverBTN = new javax.swing.JToggleButton();
        AgregarCursoBTN = new javax.swing.JToggleButton();
        EliminarCursoBTN = new javax.swing.JToggleButton();
        BuscarDocenteBTN1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        ModCursoBTN = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(77, 130, 244));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Curso");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cedula del Docente");

        IngresarCI.setBackground(new java.awt.Color(204, 204, 204));
        IngresarCI.setForeground(new java.awt.Color(0, 0, 0));
        IngresarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarCIActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Materia");

        IngresarMateria.setBackground(new java.awt.Color(204, 204, 204));
        IngresarMateria.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grupo / ID");

        IngresarGrupo.setBackground(new java.awt.Color(204, 204, 204));
        IngresarGrupo.setForeground(new java.awt.Color(0, 0, 0));

        VolverBTN.setBackground(new java.awt.Color(77, 130, 244));
        VolverBTN.setForeground(new java.awt.Color(0, 0, 0));
        VolverBTN.setText("Volver");
        VolverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBTNActionPerformed(evt);
            }
        });

        AgregarCursoBTN.setBackground(new java.awt.Color(77, 130, 244));
        AgregarCursoBTN.setForeground(new java.awt.Color(0, 0, 0));
        AgregarCursoBTN.setText("Ingresar curso nuevo");
        AgregarCursoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCursoBTNActionPerformed(evt);
            }
        });

        EliminarCursoBTN.setBackground(new java.awt.Color(77, 130, 244));
        EliminarCursoBTN.setForeground(new java.awt.Color(0, 0, 0));
        EliminarCursoBTN.setText("Eliminar Curso");
        EliminarCursoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCursoBTNActionPerformed(evt);
            }
        });

        BuscarDocenteBTN1.setBackground(new java.awt.Color(77, 130, 244));
        BuscarDocenteBTN1.setForeground(new java.awt.Color(0, 0, 0));
        BuscarDocenteBTN1.setText("Buscar");
        BuscarDocenteBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDocenteBTN1ActionPerformed(evt);
            }
        });

        ModCursoBTN.setBackground(new java.awt.Color(77, 130, 244));
        ModCursoBTN.setForeground(new java.awt.Color(0, 0, 0));
        ModCursoBTN.setText("Modificar Curso");
        ModCursoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModCursoBTNActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Para buscar y eliminar debes poner la Materia y el Grupo del curso\nPara modificar es recomendado primero buscar y \nluego modificar");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IngresarGrupo)
                    .addComponent(IngresarMateria)
                    .addComponent(IngresarCI)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VolverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgregarCursoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarDocenteBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarCursoBTN)
                            .addComponent(ModCursoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngresarCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarDocenteBTN1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ModCursoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarCursoBTN)
                            .addComponent(IngresarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngresarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VolverBTN)
                            .addComponent(AgregarCursoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BuscarDocenteBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDocenteBTN1ActionPerformed
        if (IngresarGrupo.getText().isEmpty() || IngresarMateria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La materia y el ID del grupo son necesarias para poder buscar");
        } else {
            curso BuscarCurso = new curso();
            try {
                String Grupo = IngresarGrupo.getText();
                String Materia = IngresarMateria.getText();
                BuscarCurso.setId(Grupo);
                BuscarCurso.setMateria(Materia);

                fachada.BuscarCurso(BuscarCurso);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Pone un numero");
            } catch (Exception ex) {
                System.getLogger(curso.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            String Materia = String.valueOf(BuscarCurso.getMateria());
            String ID = String.valueOf(BuscarCurso.getId());
            IngresarMateria.setText(Materia);
            IngresarGrupo.setText(ID);

        }

    }//GEN-LAST:event_BuscarDocenteBTN1ActionPerformed

    private void EliminarCursoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCursoBTNActionPerformed

        if (IngresarCI.getText().isEmpty() || IngresarGrupo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La cedula eh el id es necesario para eliminar el curso");
        } else {
            curso EliminarCurso = new curso();

            try {
                int CI = Integer.parseInt(IngresarCI.getText());
                EliminarCurso.setCIProfe(CI);
            } catch (NumberFormatException num) {
                JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");

            }
            try {
                String Id = IngresarGrupo.getText();
                EliminarCurso.setId(Id);
            } catch (NumberFormatException num) {
                JOptionPane.showMessageDialog(this, "Pon la id del grupo");
            }
            try {
                int ci = EliminarCurso.getCIProfe();
                String id = EliminarCurso.getId();

                fachada.EliminarCurso(id, ci);

            } catch (Exception ex) {
                System.getLogger(curso.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(this, "No se pudo borrar los datos");

            }
            JOptionPane.showMessageDialog(this, "Se pudo borrar los datos");

        }
    }//GEN-LAST:event_EliminarCursoBTNActionPerformed

    private void AgregarCursoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCursoBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || IngresarGrupo.getText().isEmpty() || IngresarMateria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios");
        } else {
            curso curso = new curso();
            try {
                String materia = IngresarMateria.getText();
                curso.setMateria(materia);
                String grupo = IngresarGrupo.getText();
                curso.setId(grupo);
                try {
                    int CI = Integer.parseInt(IngresarCI.getText());
                    curso.setCIProfe(CI);
                } catch (NumberFormatException num) {
                    JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");
                }
                fachada.IngresarCurso(curso);
                JOptionPane.showMessageDialog(this, "Datos guardados correctamente");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar los datos");

            }

        }

    }//GEN-LAST:event_AgregarCursoBTNActionPerformed

    private void VolverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBTNActionPerformed
        dispose();
        setVisible(false);

        CapaGrafica.ControlesAdmin volver = new ControlesAdmin();
        volver.setVisible(true);

    }//GEN-LAST:event_VolverBTNActionPerformed

    private void IngresarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarCIActionPerformed

    private void ModCursoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModCursoBTNActionPerformed
        if (IngresarCI.getText().isEmpty() || IngresarGrupo.getText().isEmpty() || IngresarMateria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Estos campos no pueden estar vacios");
        } else {
            curso curso = new curso();
            try {
                String materia = IngresarMateria.getText();
                curso.setMateria(materia);
                String grupo = IngresarGrupo.getText();
                curso.setId(grupo);
                try {
                    int CI = Integer.parseInt(IngresarCI.getText());
                    curso.setCIProfe(CI);
                } catch (NumberFormatException num) {
                    JOptionPane.showMessageDialog(this, "Pon un numero en la cedula");
                }
                String Materia = curso.getMateria();
                String Id = curso.getId();
                int ci = curso.getCIProfe();

                fachada.ModificarCurso(Materia, Id, ci);
                JOptionPane.showMessageDialog(this, "Datos modificados correctamente");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar los cambios");

            }

        }
    }//GEN-LAST:event_ModCursoBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cursos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgregarCursoBTN;
    private javax.swing.JToggleButton BuscarDocenteBTN1;
    private javax.swing.JToggleButton EliminarCursoBTN;
    private javax.swing.JTextField IngresarCI;
    private javax.swing.JTextField IngresarGrupo;
    private javax.swing.JTextField IngresarMateria;
    private javax.swing.JToggleButton ModCursoBTN;
    private javax.swing.JToggleButton VolverBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
